server.port=9090
spring.application.name=VectorDB Engine
# Disable Spring Boot banner
spring.main.banner-mode=off
# Allow large request bodies for document insertion
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
